### ISSUE TITLE
[Bug] fw_types.brs and fw_strings.brs missing from main folder

### ISSUE THREAD

**Issue by siekermantechnology** [rokudev/unit-testing-framework#2]
fw_types.brs is in the source folders of the samples, but it is missing at the top level of the project.

**Comment by siekermantechnology** [comment]
The same applies to fw_strings.brs.

**Comment by EnTerr** [comment]
Respectfully, WTF?
So apparently nobody but @siekermantechnology has tried this Piece of Software... if they did, they'd known it does not work.

Noticed this issues because could not for the life of me find FW_IsAssociativeArray() and FW_IsArray() in the project. Meaning the methods trying to use them will crash

**Comment by cdthompson** [comment]
It is a bit puzzling. I have a working version in https://github.com/veeta-tv/roku-gamp/tree/master/roku-gamp/source/unit-testing-framework but it has not been formalized into a pull request for this project.

**Comment by EnTerr** [comment]
@cdthompson - bless you for covering the library assets! Speak up - maybe they'll fix it.

I figured this piece of software was contracted to another company ("global logic" anyone?), so... if you paid for something - it better work, no?

**Comment by RokuRnD** [comment]
Thank you for filing the issue. New 1.1.0 version contains all the fixes.
